# Generated by Django 3.2.8 on 2021-10-28 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_date_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='endtime',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name='date',
            name='starttime',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='date',
            name='dates',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
