# Generated by Django 3.2.8 on 2021-10-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211028_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='date',
            name='endtime',
        ),
        migrations.AlterField(
            model_name='date',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
