# Generated by Django 3.2.8 on 2021-10-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_endttime_date_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='dates',
            field=models.ManyToManyField(blank=True, null=True, to='core.Date'),
        ),
    ]
