# Generated by Django 3.2.8 on 2021-10-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_seminar_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='starttime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
