# Generated by Django 3.2.8 on 2021-10-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211028_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='date',
        ),
        migrations.AddField(
            model_name='date',
            name='dates',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='starttime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='dates',
            field=models.ManyToManyField(blank=True, to='core.Date'),
        ),
    ]
