# Generated by Django 3.2.8 on 2021-10-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211028_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='dates',
            field=models.ManyToManyField(to='core.Date'),
        ),
    ]
