# Generated by Django 3.2.8 on 2021-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_seminar_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='dates',
            field=models.ManyToManyField(blank=True, to='core.Date'),
        ),
    ]
