# Generated by Django 3.2.8 on 2021-10-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211028_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='dates',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='date',
            name='endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='date',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
