# Generated by Django 3.2.8 on 2021-10-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211028_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='dates',
        ),
        migrations.AddField(
            model_name='date',
            name='datum',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
